### ISSUE TITLE
Random protection stone bug? need help debugging

### ISSUE THREAD

**Issue by SamGamerYT** [elBukkit/PreciousStones#143]
```
- title: mermaid
  block: BLUE_ICE
  radius: 10
  custom-height: 256
  meta-name: '&9Mermaid Stone'
  meta-autoset: false
  meta-lore:
  - '&8&l┏&8━ &9&lDESCRIPTION&r'
  - '&8&l┃ &9Radius: &f10 & Unlimited Height'
  - '&8&l┃ &9Info:'
  - '&8&l┃ &fAllows you to breathe underwater'
  - '&8&l┃ &fWithout worrying about dying'
  - '&8&l┃ &r'
  - '&8&l┃ &cWarning:'
  - '&8&l┃ &7Works for only players that are allowed'
  - '&8&l┗&8━'
  no-conflict: true
  welcome-message: true
  farewell-message: true
  mixing-group: 1
  cuboid: true
  limits:
  - 0
  - 0
  - 0
  - 0
  - 1
  - 2
  - 2
  - 3
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 10
- title: beaconator
  block: RED_CONCRETE
  radius: 20
  meta-name: '&4Beaconator Stone'
  meta-autoset: false
  meta-lore:
  - '&8&l┏&8━ &4&lDESCRIPTION&r'
  - '&8&l┃ &4Radius: &f20x20x20'
  - '&8&l┃ &4Info:'
  - '&8&l┃ &fThis stone will give you &aHaste'
  - '&8&l┃ &bJump &f& &3Speed &feffect within the radius'
  - '&8&l┃ &r'
  - '&8&l┃ &cWarning:'
  - '&8&l┃ &7Works for only players that are allowed'
  - '&8&l┗&8━'
  custom-height: 128
  cuboid: true
  dynmap-area: true
  welcome-message: true
  farewell-message: true
  mixing-group: 1
  ^potions:
  - FAST_DIGGING
  - SPEED
  - JUMP
  potion-intensity:
  - 1
  - 1
  - 1
  enable-with-redstone: true
  no-fall-damage: false
  limits:
  - 0
  - 0
  - 0
  - 0
  - 1
  - 2
  - 2
  - 3
  - 4
  - 4
  - 4
  - 4
  - 4
  - 4
  - 10
  ```
